exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - _sample
  - README.markdown
permalink: /:title
paginate: 3
assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendors

